### ISSUE TITLE
Seminário1 - revLuzzardi

### ISSUE THREAD

**Issue by pluzzardi** [yuriferreira360/BuyToHelp#2]
1. Links devem estar nas referências bibliográficas
2. Título não tem pontuação "Instituição/Curso:"
3. Não tem ponto final "Yuri Ferreira."
4. Plural "Objetivo Específico"
5. Em vários lugares tem que haver uma frase introdutória, quando há itens (Objetivos Específicos)
6. No referencial teórico os links devem estar nas referências

**Comment by yuriferreira360** [comment]
1) Adicionado referencias bibliográficas
2) Corrigido pontuações nos títulos
3) Removido ponto final
4) Plural adicionado
5) Adicionado frase introdutória em objetivos específicos
6) Referenciado de forma correta os links

**Comment by pluzzardi** [comment]
Okay Yuri, legal.

[][]’s

Prof. Luzzardi

Em ter, 2 de out de 2018 às 09:37, yuriferreira360 <notifications@github.com>
escreveu:
